name: Unit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
    inputs:
      prurl:
        description: PR Url
        required: false
      repourl:
        description: Repo Url
        required: false
      notifyemail:
        description: Notification email
        required: false
      activityid:
        description: Civi activity id
        required: false
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - drupal: '^9.1'
            civicrm: 'dev-master'
    name: ${{ github.event.inputs.repourl }} | Drupal ${{ matrix.drupal }} | CiviCRM ${{ matrix.civicrm }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 7.3
            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
            coverage: none
            tools: composer:v1
      - name: starttimer
        run: |
          cd $GITHUB_WORKSPACE
          date +%s > carrottimerfile
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
            path: ${{ steps.composercache.outputs.dir }}
            key: ${{ runner.os }}-${{ matrix.drupal }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-composer-
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Download cv
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/civicrm/cv.git civicrm-cv
          cd civicrm-cv
          COMPOSER_MEMORY_LIMIT=-1 composer install
      - name: Download Drupal
        run: |
          COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:${{ matrix.drupal }} ~/drupal --no-interaction
          cd ~/drupal
          composer config extra.enable-patching true
          composer config extra.compile-mode all
          composer config minimum-stability dev          
      - name: Download CiviCRM ${{ matrix.civicrm }}
        run: |
          cd ~/drupal
          COMPOSER_MEMORY_LIMIT=-1 composer require civicrm/civicrm-asset-plugin:'~1.1' civicrm/civicrm-{core,packages,drupal-8}:${{ matrix.civicrm }} --no-suggest
          COMPOSER_MEMORY_LIMIT=-1 composer require phpunit/phpunit:'^7.5' drush/drush
      - name: Install Drupal
        run: |
          cd ~/drupal
          ./vendor/drush/drush/drush -y -l http://civi.localhost site-install standard --db-url='mysql://root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db' --site-name=TestCivi --account-pass=admin
          chmod +w web/sites/default
      - name: Install CiviCRM
        run: |
          cd ~/drupal
          $GITHUB_WORKSPACE/civicrm-cv/bin/cv core:install --cms-base-url=http://civi.localhost -m loadGenerated=1
      - name: Get some code to test
        if: ${{ github.event.inputs.prurl != 0 }}
        run: |
          mkdir -p ~/drupal/web/sites/default/files/civicrm/ext
          cd ~/drupal/web/sites/default/files/civicrm/ext
          git clone ${{ github.event.inputs.repourl }} thingtotest
      - name: Apply PR
        if: ${{ github.event.inputs.prurl != 0 }}
        run: |
          cd  ~/drupal/web/sites/default/files/civicrm/ext/thingtotest
          curl -o thingtopatch.patch ${{ github.event.inputs.prurl }}.patch
          git apply thingtopatch.patch
      - name: Run PHPUnit
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE/civicrm-cv/bin
          export CIVICRM_UF=UnitTests
          export CIVICRM_SETTINGS=~/drupal/web/sites/default/civicrm.settings.php
          cd ~/drupal/vendor/civicrm/civicrm-core
          ../../bin/phpunit ../../../web/sites/default/files/civicrm/ext/thingtotest/tests/phpunit/CRM/
        env:
          COMPOSER_MEMORY_LIMIT: -1
          SYMFONY_DEPRECATIONS_HELPER: weak
      - name: send notification email
        if: ${{ failure() && (github.event.inputs.notifyemail != 0) }}
        uses: wadeww/send-email-action@v1
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          # This can be a temporary app password, not the real password
          password: ${{secrets.MAIL_PASSWORD}}
          subject: CiviCARROT Unit tests ${{ github.event.inputs.repourl }}
          body: Visit https://github.com/semperit/CiviCARROT/actions/runs/${{ github.run_id }} to view logs and artifacts.
          to: ${{ github.event.inputs.notifyemail }}
          from: civicarrot@gmail.com
      - name: record stats
        if: ${{ github.event.inputs.activityid != 0 }}
        run: |
          cd $GITHUB_WORKSPACE
          STARTTIME=`cat carrottimerfile`
          TIMEUSED=$(( `date +%s` - $STARTTIME ))
          # TODO: SPACEUSED=`cat carrotspacefile`         
          SPACEUSED=00
          echo "{\"type\":\"plain\",\"id\":${{ github.event.inputs.activityid }},\"bytes\":\"$SPACEUSED\",\"seconds\":$TIMEUSED,\"repo\":\"${{ github.event.inputs.repourl }}\",\"pr\":\"${{ github.event.inputs.prurl }}\",\"run_id\":\"${{ github.run_id }}\"}"
          curl --user ${{secrets.REST_USER}}:${{secrets.REST_PASS}} -X POST -H "Content-type: application/json" -d "{\"type\":\"plain\",\"id\":${{ github.event.inputs.activityid }},\"bytes\":\"$SPACEUSED\",\"seconds\":$TIMEUSED,\"repo\":\"${{ github.event.inputs.repourl }}\",\"pr\":\"${{ github.event.inputs.prurl }}\",\"run_id\":\"${{ github.run_id }}\"}" https://civicrm.io/githubaction/${{ github.event.inputs.activityid }}
